---
title: "SC21030 - HUWE1 mutant hESC neural differentiation"
author: "Stephanie Strohbuecker"
subtitle: Import CellRanger quantification with Seuratv4
output:
  html_document:
    df_print: paged
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      eval.after = "fig.cap",
                      fig.width = 12)
```

With the following we import the CellRanger quantifications into a `Seurat` object.

```{r}
RMD_file_name <- "0-6.Import_cellranger_abundances"
```

# Libraries
```{r}
library(tidyverse)
library(here)

library(Seurat)
```


```{r}
# load_all() makes the functions in the R/ directory available for usage
pkgload::load_all()
```



```{r}
cellranger_quantifications <-
  here("data", "derived_data", "CellRanger_quantification")

sample_meta <- 
  read_csv(here("data", "raw_data", "project_docs", "SC21030_ExperimentalTable.csv")) %>% 
  mutate(sample_id = `LIMS ID`) %>% 
  mutate(class.group = str_c(Genotype, Treatment, sep = " ")) %>% 
  mutate(alevin_files = str_c(
    alevin_quantifications,
    `LIMS ID`,
    "alevin/quants_mat.gz",
    sep = "/"
  )) 

# Path to output and figures directories

output_dirs <-
  str_c(here(),
        "data/derived_data",
        c("Tables", "R_objects", "Figures"),
        RMD_file_name,
        sep = "/") %>%
  set_names(c("Tables", "R_objects", "Figures"))

walk(output_dirs, ~
      generate_directories(.x))

```

```{r}
sample_path_10x <-
  dir(
    cellranger_quantifications,
    recursive = TRUE,
    pattern = "filtered_feature_bc_matrix$",
    include.dirs = TRUE,
    full.names = TRUE
  )

sample_path_10x <-
  set_names(sample_path_10x,
            str_extract(sample_path_10x, "TAN2457A[0-9]*"))
```

# Read data and generate the Seurat object

We initialise the Seurat object without filtering based on the number of detected features to allow for comparison to the alevin quantifications.
```{r}
seurat_list <-
  map2(sample_path_10x, names(sample_path_10x), function(file_path, sam_name) {
    proj_name <- sample_meta %>%
      filter(sample_id == sam_name) %>%
      pull(sample_id)
    # proj_name
    data_10x <- Read10X(data.dir = file_path)
    # data_10x
    CreateSeuratObject(
      counts = data_10x,
      project = proj_name,
      min.cells = 0,
      # include features detected in at least this many cells
      min.features = 0
    ) # include cells where at least this many features are detected
  })
```

```{r}
saveRDS(
  seurat_list,
  file = str_c(
    output_dirs["R_objects"],
    "unprocessed_cellranger_seurat_object_list.RDS",
    sep = "/"
  )
)
```
